# Generated by Django 3.2.7 on 2022-11-11 14:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'type',
                'verbose_name_plural': 'types',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='userPost')),
                ('likes', models.DecimalField(blank=True, decimal_places=0, max_digits=9999999)),
                ('comments', models.CharField(blank=True, max_length=250)),
                ('postTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited', models.DateTimeField(auto_now_add=True, null=True)),
                ('posttype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.posttype')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('-postTime',),
            },
        ),
    ]
